Improve versions test a bit
matrix-org/complement pull request #260
Opened 2021-12-02 16:52 UTC by ShadowJonathan

This has an opinionated section, even though the spec doesnt really strictly mandate version strings in an explicit sense, i thought it is reasonable to add a regex matcher in here.

2021-12-09 10:40 UTC, kegsay requested changes
I don't mind checking `unstable_features` but I do mind regexing the versions given the spec is silent on it.

2021-12-09 15:09 UTC, ShadowJonathan commented
Can I emit a warning instead? I still think that there's some degree of expectation that complement could look at.

If not, i'll remove it here and just add a spec issue, though i should probably do that anyways.

2021-12-09 22:53 UTC, kegsay commented
Warnings won't be looked at as they won't appear on success. Please just remove it for now and file a spec issue, xreffing it as a comment would be fantastic so we know why we don't regexp them.

2021-12-30 18:21 UTC, ShadowJonathan commented
@kegsay, given https://github.com/matrix-org/matrix-doc/issues/3594#issuecomment-1003130527, it turns out the spec isn't silent about this after all, I'd have to adjust the regex a little bit, but do you think that is good enough to re-add this to this test?

2022-01-17 17:03 UTC, kegsay commented
Yup, sounds good to me.

2022-03-09 09:59 UTC, kegsay commented on tests/csapi/apidoc_version_test.go
> +		versionRegex, _ := regexp.Compile("^(" + r0Regex + "|" + GlobalVersionRegex + ")$")
It is common to inline this in the global variable as `var regex = regexp.MustCompile(....)` we should probably just do that and move these lovely comments to there as well.

2022-03-09 10:00 UTC, merged