add complement test for getting joined_members after leaving.
matrix-org/complement pull request #424
Opened 2022-07-24 10:41 UTC by andrewdoh

Signed-off-by: Andrew Doh <andrewddo@gmail.com>

2022-07-25 09:33 UTC, DMRobertson requested changes

2022-07-25 09:33 UTC, DMRobertson commented on tests/csapi/apidoc_room_state_test.go
> +					match.JSONKeyEqual("error", "Getting joined members after leaving is forbidden."),
The error message here isn't part of the spec---other homeservers could choose a different message (e.g. localised for the requester's language). I think we should remove this line.

```suggestion
```

2022-07-25 09:33 UTC, DMRobertson commented on tests/csapi/apidoc_room_state_test.go
> +		t.Run("GET /rooms/:room_id/joined_members test to ensure user cannot request joined_members after leaving room", func(t *testing.T) {
```suggestion
		t.Run("GET /rooms/:room_id/joined_members is forbidden after leaving room", func(t *testing.T) {
```

2022-07-25 17:24 UTC, DMRobertson approved these changes
LGTM!

2022-07-25 17:25 UTC, DMRobertson commented
Will probably need matrix-org/synapse#13374 before merging.

2022-08-03 12:54 UTC, babolivier commented
It looks like this PR is causing issue with the CI:

```
tests/csapi/apidoc_room_state_test.go:16:2: http redeclared as imported package name
	/home/runner/work/complement/complement/tests/csapi/apidoc_room_state_test.go:4:2: previous declaration
```

This seems to be because https://github.com/matrix-org/complement/pull/415 added an import of `net/http` to this file. @andrewdoh can you fix this please? Happy to merge this PR once it's done (and CI is happy)

2022-08-03 17:10 UTC, andrewdoh commented
> It looks like this PR is having issue with the CI:
> 
> ```
> tests/csapi/apidoc_room_state_test.go:16:2: http redeclared as imported package name
> 	/home/runner/work/complement/complement/tests/csapi/apidoc_room_state_test.go:4:2: previous declaration
> ```
> 
> This seems to be because #415 added an import of `net/http` to this file. @andrewdoh can you fix this please? Happy to merge this PR once it's done (and CI is happy)

yes, its fixed. you're right, looks like we both imported http per #415.

2022-08-04 09:28 UTC, andrewdoh commented
hmmm, I suppose this means that its not working for golang implementation of the matrix protocol? I could add it tomorrow.

2022-08-11 09:19 UTC, kegsay commented
You are correct, please `runtime.SkipIf(runtime.Dendrite)`

2022-08-15 04:03 UTC, andrewdoh commented
I've updated the PR with the suggested, thanks @kegsay.

2022-08-15 10:39 UTC, DMRobertson approved these changes

2022-08-17 10:09 UTC, merged