Keep specific homeserver from blueprint
matrix-org/complement pull request #454
Opened 2022-08-22 20:27 UTC by MadLittleMods

Keep specific homeserver from blueprint. When testing in https://github.com/matrix-org/complement/pull/443, `hs1` has a room with many users with many messages in it which takes a while to construct in the blueprint which I want to stay cached, and `hs2` is my local Synapse built up over and over to test optimization changes when federating with `hs1`.

Split off from https://github.com/matrix-org/complement/pull/443

Usage:

```
COMPLEMENT_KEEP_BLUEPRINTS="fed.perf_many_messages.hs1" COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh -run TestMessagesOverFederation -p 1
```

### Dev notes

Labels on container:

```
"Labels": {
    "access_token_@charlie:hs2": "syt_Y2hhcmxpZQ_rKpoAAPGqeKxFYkgmAkU_4PG5Hd",
    "complement_blueprint": "perf_many_messages",
    "complement_context": "fed.perf_many_messages.hs2",
    "complement_hs_name": "hs2",
    "complement_pkg": "fed",
    "desktop.docker.io/ports/8008/tcp": "127.0.0.1:0",
    "desktop.docker.io/ports/8448/tcp": "127.0.0.1:0",
    "device_id@charlie:hs2": "NINFGRNLCL",
    "org.opencontainers.image.documentation": "https://github.com/matrix-org/synapse/blob/master/docker/README.md",
    "org.opencontainers.image.licenses": "Apache-2.0",
    "org.opencontainers.image.source": "https://github.com/matrix-org/synapse.git",
    "org.opencontainers.image.url": "https://matrix.org/docs/projects/server/synapse"
}
```

2022-08-22 20:28 UTC, MadLittleMods commented on internal/docker/builder.go
> +	var missingHomeservers []b.Homeserver
There are many ways to tackle this sort of behavior. What's the most idiomatic Complement way to accomplish this? Different argument name?

2022-08-22 20:29 UTC, MadLittleMods commented on internal/docker/builder.go
> +		contextStr := img.Labels[complementLabel]
Re-using the `contextStr` because it already packs in the blueprint name and homeserver name like `fed.perf_many_messages.hs1`

2022-08-22 20:31 UTC, MadLittleMods commented on internal/docker/builder.go
> +			if contextStr == keepBprint {
We could add in some regex pattern matching here to support keeping all of the homeservers in a blueprint, `fed.perf_many_messages.*`

2022-08-22 20:32 UTC, MadLittleMods commented on cmd/account-snapshot/README.md
> +This will execute the blueprint and commit the resulting images so you can push them to docker hub/gitlab. IMPORTANT: Make sure to set `HOMERUNNER_KEEP_BLUEPRINTS=your-blueprint-name` (TODO: Update)
Keeping this as a TODO to update until we settle on a way to accomplish this.

2022-09-20 11:00 UTC, kegsay requested changes
Overall happy with the idea. We need to be kinder when breaking API compatibility however.

2022-09-20 14:56 UTC, MadLittleMods commented on internal/docker/builder.go
> +	var missingHomeservers []b.Homeserver
This other comment is perfect, https://github.com/matrix-org/complement/pull/454#discussion_r975202948

Just looking for a way forward as I know the the quick and dirty way here wasn't good enough to merge.

2022-11-18 10:37 UTC, kegsay commented
What's the status with this?

2022-11-23 17:58 UTC, closed without merging