account data: add test for setting and getting
matrix-org/complement pull request #575
Opened 2022-12-21 04:30 UTC by sumnerevans

This PR adds tests for getting and setting account data.

The tests correspond to the following sytest tests:

* Can add account data
* Can get account data without syncing
* Can add account data to room
* Can get room account data without syncing

Signed-off-by: Sumner Evans <sumner@beeper.com>

2022-12-21 08:04 UTC, sumnerevans commented
looks like possibly some overlap with #574 with regards to the internal client functions

2023-01-01 03:25 UTC, anoadragon453 commented
> https://github.com/matrix-org/complement/pull/574

Heads up that https://github.com/matrix-org/complement/pull/574 has now merged.

2023-01-04 10:59 UTC, anoadragon453 requested changes

2023-01-04 10:59 UTC, anoadragon453 commented on tests/csapi/account_data_test.go
> +		resp := alice.SetGlobalAccountData(t, "com.beeper.test", map[string]interface{}{"value": "first"})
Speaking with my SCT hat on; it feels a little off to put a company's identifier into Complement for anything other than an unstable prefix. It comes across as a bit of an advertisement?

2023-01-04 10:59 UTC, anoadragon453 commented on tests/csapi/account_data_test.go
> +		})
[`SetGlobalAccountData`](https://github.com/matrix-org/complement/blob/cdad7e9d553ae6169c88a35c7a3d6d37c160397d/internal/client/client.go#L179-L181) makes use of a [`MustDoFunc`](https://github.com/matrix-org/complement/blob/cdad7e9d553ae6169c88a35c7a3d6d37c160397d/internal/client/client.go#L474-L484) call, which will already fail the test if the status code is not 2xx.

Likewise with the `GetGlobalAccountData` calls, and the get/set room variants below.

2023-02-07 00:42 UTC, squahtx approved these changes
Looks good!

2023-02-07 00:43 UTC, merged