Test the scope of a transaction IDs
matrix-org/complement pull request #613
Opened 2023-02-15 17:21 UTC by sandhose

This adds two tests, which check the current spec behaviour of transaction IDs, which are that they are scoped to a series of access tokens, and not the device ID.

The first test highlight this behaviour, by logging in with refresh token enabled, sending an event, using the refresh token and syncing with the new access token. On the sync, the transaction ID should be there, but currently in Synapse it is not.

The second test highlight that the transaction ID is not scoped to the device ID, by logging in twice with the same device ID, sending an event with the first access token, and syncing with the second access token. In that case, the sync should not contain the transaction ID, but I think it's the case in HS implementations which use the device ID to scope the transaction IDs, like Conduit.

Related: matrix-org/matrix-spec#1133, matrix-org/matrix-spec#1236, matrix-org/synapse#13064 and matrix-org/synapse#13083

2023-02-23 12:09 UTC, hughns commented
I've added a further test that checks the idempotency of requests.

2023-02-23 13:52 UTC, hughns commented on tests/csapi/txnid_scope_test.go
> +	// XXX: Synapse's implementation is broken.
I agree it looks odd and have done two things:

1. Opened a specific [issue](https://github.com/matrix-org/synapse/issues/15141) to track the bug in Synapde
2. Added further comments to clarify what is going on here

2023-02-23 17:59 UTC, clokep requested changes
Thanks @hughns! I'm just not sure it makes sense to merge this without at least one implementation passing, otherwise we don't know if the tests themselves are correct or not.

2023-02-23 18:55 UTC, hughns commented
@clokep Okay, I've removed the test entirely in https://github.com/matrix-org/complement/pull/613/commits/f829a9445899b10df5bdcbe3877e3ed8f45bed3a and we can add it back in another PR later on 👍

2023-02-28 17:12 UTC, hughns commented on tests/csapi/txnid_test.go
> +	runtime.SkipIf(t, runtime.Synapse)
@sandhose this doesn't match the comment above

2023-03-04 23:27 UTC, hughns commented
As per discussion in #synapse-dev:matrix.org I've pulled the definitely good tests out in to https://github.com/matrix-org/complement/pull/622 for separate review.

2023-04-18 17:15 UTC, hughns commented
@erikjohnston I've given this a severe rebase. It doesn't require review at the moment as the test does not pass for any implementation. Please can it be made draft?

2023-05-26 16:45 UTC, hughns commented
This PR should be closed as MSC3970 has been accepted and so new tests are in https://github.com/matrix-org/complement/pull/637

2023-05-26 16:46 UTC, closed without merging